/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_BatchRenderer2D */

#ifndef _Included_sp_graphics_BatchRenderer2D
#define _Included_sp_graphics_BatchRenderer2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_BatchRenderer2D
	* Method:    jniCreate
	* Signature: (II)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_BatchRenderer2D_jniCreate
		(JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
