/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Font */

#ifndef _Included_sp_graphics_Font
#define _Included_sp_graphics_Font
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Font
	* Method:    jniCreate
	* Signature: (Ljava/lang/String;F)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Font_jniCreate__Ljava_lang_String_2F
		(JNIEnv *, jclass, jstring, jfloat);

	/*
	* Class:     sp_graphics_Font
	* Method:    jniCreate
	* Signature: (Ljava/nio/Buffer;IF)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Font_jniCreate__Ljava_nio_Buffer_2IF
		(JNIEnv *, jclass, jobject, jint, jfloat);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_SetScale
	* Signature: (JFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Font_native_1SetScale
		(JNIEnv *, jclass, jlong, jfloat, jfloat);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_GetScale_X
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Font_native_1GetScale_1X
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_GetScale_Y
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Font_native_1GetScale_1Y
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_GetSize
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Font_native_1GetSize
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_GetTexture
	* Signature: (J)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Font_native_1GetTexture
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    native_GetID
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Font_native_1GetID
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Font
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Font_jniDelete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
