/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Renderable2D */

#ifndef _Included_sp_graphics_Renderable2D
#define _Included_sp_graphics_Renderable2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    jniCreate
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Renderable2D_jniCreate__
		(JNIEnv *, jclass);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    jniCreate
	* Signature: (FFFFFI)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Renderable2D_jniCreate__FFFFFI
		(JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetPosition_X
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Renderable2D_native_1GetPosition_1X
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetPosition_Y
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Renderable2D_native_1GetPosition_1Y
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetPosition_Z
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Renderable2D_native_1GetPosition_1Z
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_SetPosition
	* Signature: (JFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderable2D_native_1SetPosition
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetSize_X
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Renderable2D_native_1GetSize_1X
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetSize_Y
	* Signature: (J)F
	*/
	JNIEXPORT jfloat JNICALL Java_sp_graphics_Renderable2D_native_1GetSize_1Y
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_SetSize
	* Signature: (JFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderable2D_native_1SetSize
		(JNIEnv *, jclass, jlong, jfloat, jfloat);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_SetColor
	* Signature: (JI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderable2D_native_1SetColor
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetColor
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Renderable2D_native_1GetColor
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_GetTexture
	* Signature: (J)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Renderable2D_native_1GetTexture
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_SetTexture
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderable2D_native_1SetTexture
		(JNIEnv *, jclass, jlong, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_IsVisible
	* Signature: (J)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_graphics_Renderable2D_native_1IsVisible
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    native_SetVisible
	* Signature: (JZ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderable2D_native_1SetVisible
		(JNIEnv *, jclass, jlong, jboolean);

	/*
	* Class:     sp_graphics_Renderable2D
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderable2D_jniDelete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
