/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Renderer2D */

#ifndef _Included_sp_graphics_Renderer2D
#define _Included_sp_graphics_Renderer2D
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_Push
	* Signature: (JLjava/nio/Buffer;Z)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1Push
		(JNIEnv *, jclass, jlong, jobject, jboolean);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_Pop
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1Pop
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_SetRenderTarget
	* Signature: (JI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1SetRenderTarget
		(JNIEnv *, jclass, jlong, jint);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_GetRenderTarget
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Renderer2D_native_1GetRenderTarget
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_SetPostEffects
	* Signature: (JZ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1SetPostEffects
		(JNIEnv *, jclass, jlong, jboolean);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_GetPostEffects
	* Signature: (J)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_graphics_Renderer2D_native_1GetPostEffects
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_AddPostEffectsPass
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1AddPostEffectsPass
		(JNIEnv *, jclass, jlong, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_SetMask
	* Signature: (JJLjava/nio/ByteBuffer;)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1SetMask
		(JNIEnv *, jclass, jlong, jlong, jobject);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_Begin
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1Begin
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_Submit
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1Submit
		(JNIEnv *, jclass, jlong, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_DrawLine
	* Signature: (JFFFFFI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1DrawLine
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_DrawRect
	* Signature: (JFFFFI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1DrawRect
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_DrawString
	* Signature: (JLjava/lang/String;FFJI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1DrawString
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jlong, jint);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_FillRect
	* Signature: (JFFFFI)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1FillRect
		(JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_End
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1End
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    native_Present
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_native_1Present
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Renderer2D
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Renderer2D_jniDelete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
