/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_Texture */

#ifndef _Included_sp_graphics_Texture
#define _Included_sp_graphics_Texture
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_Texture
	* Method:    native_SetWrap
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Texture_native_1SetWrap
		(JNIEnv *, jclass, jint);

	/*
	* Class:     sp_graphics_Texture
	* Method:    native_SetFilter
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Texture_native_1SetFilter
		(JNIEnv *, jclass, jint);

	/*
	* Class:     sp_graphics_Texture
	* Method:    jniCreate
	* Signature: (III)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Texture_jniCreate__III
		(JNIEnv *, jclass, jint, jint, jint);

	/*
	* Class:     sp_graphics_Texture
	* Method:    jniCreate
	* Signature: (Ljava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Texture_jniCreate__Ljava_lang_String_2
		(JNIEnv *, jclass, jstring);

	/*
	* Class:     sp_graphics_Texture
	* Method:    jniCreate
	* Signature: (I)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_Texture_jniCreate__I
		(JNIEnv *, jclass, jint);

	/*
	* Class:     sp_graphics_Texture
	* Method:    native_Bind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Texture_native_1Bind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Texture
	* Method:    native_Unbind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Texture_native_1Unbind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Texture
	* Method:    native_GetID
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Texture_native_1GetID
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Texture
	* Method:    native_GetWidth
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Texture_native_1GetWidth
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Texture
	* Method:    native_GetHeight
	* Signature: (J)I
	*/
	JNIEXPORT jint JNICALL Java_sp_graphics_Texture_native_1GetHeight
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_Texture
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_Texture_jniDelete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
