/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_shaders_Shader */

#ifndef _Included_sp_graphics_shaders_Shader
#define _Included_sp_graphics_shaders_Shader
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    jniCreate
	* Signature: (Ljava/lang/String;Ljava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_shaders_Shader_jniCreate
		(JNIEnv *, jclass, jstring, jstring);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_jniDelete
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform1f
	* Signature: (JLjava/lang/String;F)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform1f
		(JNIEnv *, jclass, jlong, jstring, jfloat);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform1fv
	* Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;I)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform1fv
		(JNIEnv *, jclass, jlong, jstring, jobject, jint);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform1i
	* Signature: (JLjava/lang/String;I)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform1i
		(JNIEnv *, jclass, jlong, jstring, jint);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform1iv
	* Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;I)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform1iv
		(JNIEnv *, jclass, jlong, jstring, jobject, jint);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform2f
	* Signature: (JLjava/lang/String;FF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform2f
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform3f
	* Signature: (JLjava/lang/String;FFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform3f
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform4f
	* Signature: (JLjava/lang/String;FFFF)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform4f
		(JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat, jfloat);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniformMat4
	* Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniformMat4
		(JNIEnv *, jclass, jlong, jstring, jobject);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_SetUniform
	* Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1SetUniform
		(JNIEnv *, jclass, jlong, jstring, jobject);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_ResolveAndSetUniform
	* Signature: (JILjava/nio/ByteBuffer;)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1ResolveAndSetUniform
		(JNIEnv *, jclass, jlong, jint, jobject);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_ResolveAndSetUniforms
	* Signature: (JLjava/nio/ByteBuffer;I)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1ResolveAndSetUniforms
		(JNIEnv *, jclass, jlong, jobject, jint);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_Bind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1Bind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_Unbind
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_shaders_Shader_native_1Unbind
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_shaders_Shader
	* Method:    native_HashUniform
	* Signature: (JLjava/lang/String;)Z
	*/
	JNIEXPORT jboolean JNICALL Java_sp_graphics_shaders_Shader_native_1HashUniform
		(JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
