/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_postfx_PostEffectsPass */

#ifndef _Included_sp_graphics_postfx_PostEffectsPass
#define _Included_sp_graphics_postfx_PostEffectsPass
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_postfx_PostEffectsPass
	* Method:    jniCreate
	* Signature: (J)J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_postfx_PostEffectsPass_jniCreate
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_postfx_PostEffectsPass
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_postfx_PostEffectsPass_jniDelete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
