/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sp_graphics_postfx_PostEffects */

#ifndef _Included_sp_graphics_postfx_PostEffects
#define _Included_sp_graphics_postfx_PostEffects
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sp_graphics_postfx_PostEffects
	* Method:    native_Push
	* Signature: (JJ)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_postfx_PostEffects_native_1Push
		(JNIEnv *, jclass, jlong, jlong);

	/*
	* Class:     sp_graphics_postfx_PostEffects
	* Method:    native_Pop
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_postfx_PostEffects_native_1Pop
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     sp_graphics_postfx_PostEffects
	* Method:    jniCreate
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_sp_graphics_postfx_PostEffects_jniCreate
		(JNIEnv *, jclass);

	/*
	* Class:     sp_graphics_postfx_PostEffects
	* Method:    jniDelete
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_sp_graphics_postfx_PostEffects_jniDelete
		(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
